title: ANNO Guide
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# 
baseurl: "../"
url: "http://anno.getforge.io/"

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

defaults:
  -
    scope:
      path: "1503"
      type: "pages"
    values:
      layout: "1503"
  -
    scope:
      path: "1602"
      type: "pages"
    values:
      layout: "1602"
